export const mockCollections = [
  { id: 1, name: "Frontend Guide", icon: "Code2", color_label: "#60a5fa", created_at: "2026-04-20T10:55:03.093Z" },
  { id: 2, name: "DSA Prep", icon: "BrainCircuit", color_label: "#f87171", created_at: "2026-04-20T10:55:03.153Z" },
  { id: 3, name: "System Design", icon: "Network", color_label: "#34d399", created_at: "2026-04-20T10:55:03.161Z" },
  { id: 4, name: "Dev Tools & Setup", icon: "Terminal", color_label: "#fbbf24", created_at: "2026-04-20T10:55:03.170Z" },
  { id: 5, name: "CS Core Subjects", icon: "BookOpen", color_label: "#a78bfa", created_at: "2026-04-20T10:55:03.180Z" },
  { id: 6, name: "Interview Prep", icon: "ClipboardCheck", color_label: "#fb7185", created_at: "2026-04-20T10:55:03.190Z" }
];

export const mockResources = [
  { id: 1, title: "React Hooks Deep Dive (useEffect, useMemo)", description: "A comprehensive video guide explaining the nuances of React hooks, focusing on memoization and side effects.", type: "video", url: "https://youtube.com/xyz", tags: "React, Hooks", status: "In Progress", priority: "High", collectionId: 1, pinned: false },
  { id: 2, title: "Build a Fullstack App with Firebase", description: "Learn how to integrate Firebase authentication and database with a React application from scratch.", type: "article", url: "https://dev.to/xyz", tags: "React, Firebase, Auth", status: "Not Started", priority: "Medium", collectionId: 1, pinned: false },
  { id: 3, title: "LeetCode Blind 75 List", description: "The definitive list of 75 essential LeetCode questions to prepare for tech interviews, covering all major data structures.", type: "article", url: "https://leetcode.com/list/xyz", tags: "DSA, Arrays, Graphs", status: "In Progress", priority: "High", collectionId: 2, pinned: false },
  { id: 4, title: "Dynamic Programming Patterns (Must Know)", description: "Break down complex DP problems into recognizable patterns with intuitive explanations.", type: "video", url: "https://youtube.com/abc", tags: "DP, DSA", status: "Not Started", priority: "High", collectionId: 2, pinned: false },
  { id: 5, title: "System Design Basics: Load Balancers", description: "Understand how load balancers distribute traffic and ensure high availability in distributed systems.", type: "video", url: "https://youtube.com/def", tags: "SystemDesign, Backend", status: "Not Started", priority: "High", collectionId: 3, pinned: false },
  { id: 6, title: "Design URL Shortener (Case Study)", description: "A classic system design interview question: architecting a scalable URL shortening service like Bitly.", type: "article", url: "https://medium.com/xyz", tags: "SystemDesign, CaseStudy", status: "Not Started", priority: "Medium", collectionId: 3, pinned: false },
  { id: 7, title: "Git & GitHub Crash Course", description: "Master version control fundamentals, branching strategies, and collaboration workflows.", type: "video", url: "https://youtube.com/git", tags: "Git, DevTools", status: "Completed", priority: "Low", collectionId: 4, pinned: false },
  { id: 8, title: "Docker for Beginners (Hands-on)", description: "Containerize your applications step-by-step using Docker runtimes and Compose.", type: "video", url: "https://youtube.com/docker", tags: "Docker, DevOps", status: "Not Started", priority: "Medium", collectionId: 4, pinned: false },
  { id: 9, title: "Operating Systems Notes (Processes & Threads)", description: "Detailed class notes on process management, concurrency, and thread synchronization.", type: "pdf", url: "localfile", tags: "OS, CoreCS", status: "In Progress", priority: "Medium", collectionId: 5, pinned: false },
  { id: 10, title: "DBMS Normalization Explained Clearly", description: "A simplified breakdown of database normal forms (1NF to BCNF) to prevent data anomalies.", type: "article", url: "https://geeksforgeeks.org/dbms", tags: "DBMS, CoreCS", status: "Completed", priority: "Low", collectionId: 5, pinned: false },
  { id: 11, title: "Top 50 Interview Questions (Frontend)", description: "A curated list of HTML, CSS, JavaScript, and framework-specific interview questions.", type: "article", url: "https://interviewprep.com", tags: "Interview, Frontend", status: "Not Started", priority: "High", collectionId: 6, pinned: false },
  { id: 12, title: "Behavioral Interview Prep Guide", description: "How to structure your answers using the STAR format for leadership and team-conflict behavioral questions.", type: "note", url: "localfile", tags: "Interview, HR", status: "Not Started", priority: "Low", collectionId: 6, pinned: false },
  { id: 13, title: "Clean Code: A Handbook of Agile Software Craftsmanship", description: "The definitive guide on writing readable, maintainable code by Robert C. Martin.", type: "book", url: "localfile", tags: "Refactoring, Books", status: "Not Started", priority: "Medium", collectionId: 1, pinned: false },
  { id: 14, title: "Vite JS Official Documentation", description: "Next Generation Frontend Tooling. Get ready for an unopinionated, blazing fast development experience.", type: "website", url: "https://vitejs.dev", tags: "Tooling, Builds", status: "Completed", priority: "Low", collectionId: 4, pinned: false },
  { id: 15, title: "System Architecture Diagram Flow", description: "High level topological overview of the new microservices boundaries.", type: "image", url: "https://images.unsplash.com/photo-1542831371-29b0f74f9713", tags: "SystemDesign, Diagram", status: "Completed", priority: "Low", collectionId: 3, pinned: false },
  { id: 16, title: "useDebounce Hook Implementation", description: "A highly reusable custom hook for debouncing fast-changing values like search inputs.", type: "code", url: "https://gist.github.com/react", tags: "React, Snippet", status: "Completed", priority: "High", collectionId: 1, pinned: true }
];
